# Generated by Django 4.1 on 2023-07-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_quiz_chapter_id_quiz_course_id_delete_chapterquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course_id',
        ),
    ]
