# Generated by Django 4.1 on 2023-07-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_quiz_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_content',
            field=models.TextField(default='Something'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='long_description',
            field=models.TextField(default='Something'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(default='Something'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='IT', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='muliplechoicesanswer',
            name='answer1',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='muliplechoicesanswer',
            name='answer2',
            field=models.CharField(default='B', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='muliplechoicesanswer',
            name='answer3',
            field=models.CharField(default='C', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='muliplechoicesanswer',
            name='answer4',
            field=models.CharField(default='D', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.TextField(default='Something'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='avgtime',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='qtype',
            field=models.TextField(choices=[('multichoices', 'multichoices'), ('T/F', 'T/F'), ('pagragraph', 'PARAGRAPH')], default='paragrap'),
            preserve_default=False,
        ),
    ]
